run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - goconst
    - misspell
    - gofmt
    - goimports
    - gocyclo
    - lll
    - ineffassign
    - unconvert
    - unparam
    - unused
    - gosec
    - prealloc

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: vendor/
      linters:
        - "*"

