version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - goconst
    - misspell
    - gocyclo
    - gosec
    - lll
    - prealloc
    - unconvert
    - unparam
    - unused

formatters:
  enable:
    - gofmt
    - goimports

settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  misspell:
    locale: US

exclusions:
  generated: lax
  presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
  rules:
    - linters:
        - gosec
      path: _test\.go
    - linters:
        - '*'
      path: vendor/
  paths:
    - third_party$
    - builtin$
    - examples$

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: vendor/
      linters:
        - "*"
