version: "2"
run:
  tests: true
linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - lll
    - misspell
    - prealloc
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
      - linters:
          - '*'
        path: vendor/
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
