version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - goconst
    - misspell
    - gocyclo
    - gosec
    - lll
    - prealloc
    - unconvert
    - unparam
    - unused

linters-settings:
  gocyclo:
    min-complexity: 15
  lll:
    line-length: 120
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: vendor/
      linters:
        - "*"
