package app

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateConfig_Validate_EmptyRootPath(t *testing.T) {
	cfg := GenerateConfig{}
	err := cfg.Validate()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "root path is required")
}

func TestGenerateConfig_Validate_NonExistentPath(t *testing.T) {
	cfg := GenerateConfig{
		RootPath: "/nonexistent/path/that/does/not/exist",
	}
	err := cfg.Validate()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "cannot access root path")
}

func TestGenerateConfig_Validate_FileNotDirectory(t *testing.T) {
	tmpFile, err := os.CreateTemp("", "test-file-*.txt")
	require.NoError(t, err)
	defer os.Remove(tmpFile.Name())
	tmpFile.Close()

	cfg := GenerateConfig{
		RootPath: tmpFile.Name(),
	}
	err = cfg.Validate()
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "root path must be a directory")
}

func TestGenerateConfig_Validate_ValidDirectory(t *testing.T) {
	tmpDir := t.TempDir()

	cfg := GenerateConfig{
		RootPath: tmpDir,
	}
	err := cfg.Validate()
	assert.NoError(t, err)

	absPath, _ := filepath.Abs(tmpDir)
	assert.Equal(t, absPath, cfg.RootPath, "should normalize to absolute path")
}

func TestGenerateConfig_Validate_RelativePath(t *testing.T) {
	wd, err := os.Getwd()
	require.NoError(t, err)

	cfg := GenerateConfig{
		RootPath: ".",
	}
	err = cfg.Validate()
	assert.NoError(t, err)
	assert.Equal(t, wd, cfg.RootPath)
}

func TestGenerateConfig_GenerateOutputPath_CustomPath(t *testing.T) {
	cfg := GenerateConfig{
		OutputPath: "/custom/path/output.md",
	}
	assert.Equal(t, "/custom/path/output.md", cfg.GenerateOutputPath())
}

func TestGenerateConfig_GenerateOutputPath_AutoGenerated(t *testing.T) {
	cfg := GenerateConfig{}
	path := cfg.GenerateOutputPath()

	assert.Contains(t, path, "shotgun-prompt-")
	assert.True(t, filepath.Ext(path) == ".md", "should have .md extension")
}

func TestGenerateConfig_GenerateOutputPath_TimestampFormat(t *testing.T) {
	cfg := GenerateConfig{}
	path := cfg.GenerateOutputPath()

	assert.Regexp(t, `shotgun-prompt-\d{8}-\d{6}\.md`, path)
}

func TestGenerateResult_Structure(t *testing.T) {
	result := GenerateResult{
		Content:           "test content",
		OutputPath:        "/path/to/output.md",
		FileCount:         10,
		ContentSize:       1024,
		TokenEstimate:     256,
		CopiedToClipboard: true,
	}

	assert.Equal(t, "test content", result.Content)
	assert.Equal(t, "/path/to/output.md", result.OutputPath)
	assert.Equal(t, 10, result.FileCount)
	assert.Equal(t, int64(1024), result.ContentSize)
	assert.Equal(t, int64(256), result.TokenEstimate)
	assert.True(t, result.CopiedToClipboard)
}
